#!/usr/bin/env python3
"""Run the metadata conformance fixtures against ANY reader, not just this one.

Built for panduck, who is implementing document metadata across five readers at once.
Five hand-written expectations are five chances to encode one misreading five ways --
or, worse, four correctly and once not, which reads as a typo rather than a
disagreement. One instrument, five readers.

WHAT THIS IS NOT: an independent oracle. `expected/*.tsv` was generated by THIS repo's
`read_pandoc_ast` and then reviewed line by line against the spec. So a reader that
matches has agreed with the reference implementation, which is weaker than agreeing
with the specification. Where the two could differ, the README says which rule each
fixture is pinning, so a disagreement can be argued rather than merely reported.

Usage:
    ./check_metadata_fixtures.py                      # this repo, AST inputs
    ./check_metadata_fixtures.py --duckdb ../../../duckdb_panduck/build/release/duckdb \
        --load .../panduck.duckdb_extension --reader "read_latex('{path}')" --input src
"""

import argparse
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[2]

# fixture -> (source file, pandoc reader name). The AST is derived from the source by
# `make -C test/fixtures/metadata ast`, so the source is the thing under version
# control that a human can read and a different reader can consume directly.
FIXTURES = {
    "frontmatter_and_body": ("frontmatter_and_body.md", "markdown"),
    "empty_field_yaml": ("empty_field_yaml.md", "markdown"),
    "empty_field_org": ("empty_field_org.org", "org"),
    "multi_author_concat": ("multi_author_concat.org", "org"),
    "multi_author_list": ("multi_author_list.tex", "latex"),
    "value_kinds": ("value_kinds.md", "markdown"),
}

ROW_SQL = (
    "SELECT b.element_order || chr(9) || b.kind || chr(9) || b.element_type"
    " || chr(9) || b.level || chr(9) || b.encoding"
    " || chr(9) || CASE WHEN b.content IS NULL THEN '<NULL>' ELSE b.content END"
    " || chr(9) || CASE WHEN b.attributes['key'] IS NULL THEN '<NONE>' ELSE b.attributes['key'] END"
    " FROM (SELECT unnest({reader}) AS b) ORDER BY b.element_order;"
)


def normalise(row: str) -> tuple:
    """One row, with the differences that are NOT the property removed.

    `content` is compared with NULL and '' treated as the same, because three shipped
    implementations disagree on which one means "this element carries no content" --
    webbed emits NULL for a container, this repo emits '' -- and the spec never said.
    Pinning either spelling here would fail a conforming reader for a difference the
    specification does not express. The divergence is REPORTED rather than encoded;
    see README.md, "The NULL-versus-empty divergence".
    """
    cols = row.split("\t")
    if len(cols) == 7 and cols[5] == "<NULL>":
        cols[5] = ""
    return tuple(cols)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--duckdb", default=str(REPO / "build/release/duckdb"))
    ap.add_argument("--load", default=str(REPO / "build/release/extension/duck_block_utils/duck_block_utils.duckdb_extension"))
    ap.add_argument("--reader", default="read_pandoc_ast('{path}')")
    ap.add_argument("--input", choices=("ast", "src"), default="ast")
    ap.add_argument("--only", default=None, help="run one fixture by name")
    args = ap.parse_args()

    duckdb = pathlib.Path(args.duckdb)
    if not duckdb.exists():
        print(f"SKIP: no duckdb at {duckdb}")
        return 0

    names = [args.only] if args.only else sorted(FIXTURES)
    failed = 0
    for name in names:
        src, _fmt = FIXTURES[name]
        path = HERE / ("ast/" + name + ".json" if args.input == "ast" else "src/" + src)
        if not path.exists():
            print(f"FAIL: {name} -- no input at {path}")
            failed += 1
            continue
        sql = ROW_SQL.format(reader=args.reader.format(path=path))
        if args.load:
            sql = f"LOAD '{args.load}'; " + sql
        proc = subprocess.run(
            [str(duckdb), "-unsigned", "-init", "/dev/null", "-noheader", "-list", "-c", sql],
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            print(f"FAIL: {name} -- the reader errored, so this is not a conformance result.")
            print("      " + "\n      ".join(proc.stderr.strip().splitlines()[:4]))
            failed += 1
            continue
        got = [normalise(r) for r in proc.stdout.strip().splitlines() if r.strip()]
        want = [normalise(r) for r in (HERE / f"expected/{name}.tsv").read_text().splitlines() if r.strip()]
        if got == want:
            print(f"  OK   {name} -- {len(want)} elements")
            continue
        failed += 1
        print(f"\nFAIL: {name}")
        for i in range(max(len(got), len(want))):
            g = got[i] if i < len(got) else None
            w = want[i] if i < len(want) else None
            if g != w:
                print(f"      row {i}: expected {w}")
                print(f"               got {g}")
        print()
    if failed:
        print(f"\n{failed} of {len(names)} fixtures do not conform.")
        return 1
    print(f"OK: {len(names)} metadata fixtures conform.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
